README redesign
auth0/Lock.Android pull request #651
Opened 2022-10-19 12:40 UTC by poovamraj

### Changes
- Changed to new README design
- Added code of conduct page

2022-10-19 15:21 UTC, stevehobbsdev submitted a review, later dismissed
LGTM, just left a couple of things

2022-10-19 15:21 UTC, stevehobbsdev commented on README.md
> +</p>
These can now be added from the CDN and the local files deleted, see https://auth0.slack.com/archives/C0414QJGXG9/p1666171760950799?thread_ts=1666170245.671199&cid=C0414QJGXG9

2022-10-19 15:21 UTC, stevehobbsdev commented on README.md
> +- [Auth0's code of conduct guidelines](https://github.com/auth0/Lock.Android/blob/main/CODE-OF-CONDUCT.md)
Could this just be a relative link?

2022-10-25 08:56 UTC, frederikprijck requested changes

2022-10-25 08:56 UTC, frederikprijck commented on README.md
> +- [Examples](https://github.com/auth0/auth0.android/blob/main/EXAMPLES.md)
```suggestion
- [Examples](https://github.com/auth0/Lock.android/blob/main/EXAMPLES.md)
```

2022-10-25 09:02 UTC, frederikprijck approved these changes

2022-10-26 08:48 UTC, merged